import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";

const inter = Inter({
  variable: '--font-Inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Travel Trucks App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <TanStackProvider>
          <Header/>
        <main>{children}</main>
         </TanStackProvider>
        
      </body>
    </html>
  );
}
